<?php


/**
 * Kiwip Framework
 *
 * @package Kiwip Framework
 * @since Kiwip Framework 0.1
 * @author Benjamin Cabanes | http://slapandthink.com | @slapandthink
 * @version 0.1
 * @copyright Benjamin Cabanes
 */
class Kiwip_Framework{

	public $framework_url     = 'http://slapandthink.com';
	public $framework_version = '0.1 beta';
	
	public $theme_options     = '';
	public $custom_post_type  = '';
	public $widget            = '';
	
	public $framework_options = true;

	public $framework_shortcodes = true;


	/**
	 * Construct
	 * Defines some globals and initialize some Class
	 * @since Kiwip Framework 0.1
	 */
	public function __construct(){

		/**
		 * Define the text domain of the current activated theme using the Kiwip Framework.
		 * This is used for the translation of the elements generated by the Framework (like admin message)
		 */
		define(KIWIP_TEXTDOMAIN, wp_get_theme('TextDomain'));

		/**
		 * Define PATH and URL of the Framework
		 */
		define(KIWIP_PATH, TEMPLATEPATH.'/Kiwip_Framework/');
		define(KIWIP_URL, get_bloginfo('template_url').'/Kiwip_Framework/');

		/* Adding the Kiwip Framework Options */
		$this->add_framework_options();

		/* Test if framework's shortcode is enable */
		if($this->framework_shortcodes){
			require_once KIWIP_PATH.'Shortcodes/Kiwip_Shortcodes.php';
			return $this->framework_shortcodes == new Kiwip_Shortcodes();
		}
	}


	/**
	 * Add Theme Options
	 * @since Kiwip Framework 0.1
	 */
	public function add_theme_options($args, $sections, $extra_tabs){
		//require_once KIWIP_PATH.'Theme_Options/Kiwip_Theme_Options.php';
		$this->theme_options = new Kiwip_Theme_Options($args, $sections, $extra_tabs);
	}

	/**
	 * Add Custom Post Type
	 * @param string $name
	 * @param array $args
	 * @param array $labels
	 * @since Kiwip Framework 0.1
	 */
	public function add_custom_post_type($name, $config=array(), $args=array(), $labels=array()){
		ob_start();
		require_once KIWIP_PATH.'Custom_Post_Type/Kiwip_Custom_Post_Type.php';
		require_once KIWIP_PATH.'Custom_Post_Type/Kiwip_Taxonomy.php';
		require_once KIWIP_PATH.'Custom_Post_Type/Kiwip_Meta_Box.php';
		require_once KIWIP_PATH.'Custom_Post_Type/Kiwip_Helper.php';
		return $this->custom_post_type = new Kiwip_Custom_Post_Type($name, $config, $args, $labels);
	}

	/**
	 * Add Widgets
	 * @since Kiwip Framework 0.1
	 */
	public function add_widget(){
		require_once KIWIP_PATH.'Widgets/Kiwip_Widgets.php';
		$this->widgets = new Kiwip_Widgetd();
	}

	/**
	 * Framework Options
	 * Display additionnal options to opitmise Wordpress
	 * @since Kiwip Framework 0.1
	 */
	public function add_framework_options(){
		if($this->framework_options == true){
			require_once KIWIP_PATH.'Theme_Options/Kiwip_Theme_Options.php';
			require_once KIWIP_PATH.'Framework_Options/Framework_Options.php';
			return $this->framework_options == new Framework_Options();
		}
	}

}


